### ISSUE TITLE
In the 2D GCVT, how do I set the density to 0？

### ISSUE THREAD

**Issue by for-heart-peace** [orzzzjq/gCentroidal-Voronoi-Tessellation#4]
Hello,
I generated a CVT for the areas in the image that are not black by setting the density to 0 for black areas and 1-10 for colored areas. However, the resulting CVT is very poor. Is it because I set the density incorrectly? The white areas in the image indicate the positions of the seed points.
![QQ截图20230330211830](https://user-images.githubusercontent.com/24697890/228848588-989637cd-ce22-4169-bf13-ea4e28eeb851.png)

**Comment by for-heart-peace** [comment]
Setting the density to 0 results in very unreasonable errors, so I set the density of black areas to 1e-6. The figure above shows this. I am looking forward to your reply.
Best wishes.

**Comment by orzzzjq** [comment]
I think what you are trying to do is a constrained version of CVT, which is a different problem. We didn't consider this case when designing GCVT. You may simply drop out the points outside the region. If you want the correct number of points in the region, you may need to modify GCVT for this purpose. Some points that I can think of:

1. Initializing the seeds in the restricted region.
2. Modify the step size of the over-relaxed Lloyds method (currently it is 2.0, and <=1.0 should be safe for the constrained version).
3. Maybe don't use the subsampling trick (set depth=1?), which may also cause issues in the constrained version.

You may also check this repo: https://github.com/orzzzjq/Surface-Remesher, which I remember I've done something similar...

**Comment by for-heart-peace** [comment]
Thank you for your reply. I have tried to drop out the points outside the region, but I have obtained seed points that are not distributed according to density. I will follow your suggestions. 
Thanks again!
